// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	Req
	Ack
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	A string `protobuf:"bytes,1,opt,name=a" json:"a,omitempty"`
	B int64  `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Req) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type Ack struct {
	V string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ack) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func init() {
	proto.RegisterType((*Req)(nil), "pb.Req")
	proto.RegisterType((*Ack)(nil), "pb.Ack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Test service

type TestClient interface {
	ReqSvr(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Ack, error)
	StreamSvr(ctx context.Context, opts ...grpc.CallOption) (Test_StreamSvrClient, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) ReqSvr(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/pb.Test/ReqSvr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) StreamSvr(ctx context.Context, opts ...grpc.CallOption) (Test_StreamSvrClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Test_serviceDesc.Streams[0], c.cc, "/pb.Test/StreamSvr", opts...)
	if err != nil {
		return nil, err
	}
	x := &testStreamSvrClient{stream}
	return x, nil
}

type Test_StreamSvrClient interface {
	Send(*Req) error
	Recv() (*Ack, error)
	grpc.ClientStream
}

type testStreamSvrClient struct {
	grpc.ClientStream
}

func (x *testStreamSvrClient) Send(m *Req) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testStreamSvrClient) Recv() (*Ack, error) {
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Test service

type TestServer interface {
	ReqSvr(context.Context, *Req) (*Ack, error)
	StreamSvr(Test_StreamSvrServer) error
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_ReqSvr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).ReqSvr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Test/ReqSvr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).ReqSvr(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_StreamSvr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServer).StreamSvr(&testStreamSvrServer{stream})
}

type Test_StreamSvrServer interface {
	Send(*Ack) error
	Recv() (*Req, error)
	grpc.ServerStream
}

type testStreamSvrServer struct {
	grpc.ServerStream
}

func (x *testStreamSvrServer) Send(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testStreamSvrServer) Recv() (*Req, error) {
	m := new(Req)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqSvr",
			Handler:    _Test_ReqSvr_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSvr",
			Handler:       _Test_StreamSvr_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb.proto",
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe4, 0x62, 0x0e, 0x4a, 0x2d, 0x14,
	0xe2, 0xe1, 0x62, 0x4c, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4c, 0x04, 0xf1, 0x92,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x18, 0x93, 0x94, 0x84, 0xb9, 0x98, 0x1d, 0x93, 0xb3,
	0x41, 0x82, 0x65, 0x30, 0x25, 0x65, 0x46, 0x9e, 0x5c, 0x2c, 0x21, 0xa9, 0xc5, 0x25, 0x42, 0x32,
	0x5c, 0x6c, 0x41, 0xa9, 0x85, 0xc1, 0x65, 0x45, 0x42, 0xec, 0x7a, 0x05, 0x49, 0x7a, 0x41, 0xa9,
	0x85, 0x52, 0x60, 0x86, 0x63, 0x72, 0xb6, 0x12, 0x83, 0x90, 0x32, 0x17, 0x67, 0x70, 0x49, 0x51,
	0x6a, 0x62, 0x2e, 0x0e, 0x05, 0x1a, 0x8c, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0xd7, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x81, 0x3d, 0xa0, 0xe5, 0x99, 0x00, 0x00, 0x00,
}
